#pragma once

static const char* ExtraDataTypeName(RE::ExtraDataType t) {
    switch (t) {
        case RE::ExtraDataType::kNone:
            return "None";
        case RE::ExtraDataType::kHavok:
            return "ExtraHavok";
        case RE::ExtraDataType::kCell3D:
            return "ExtraCell3D";
        case RE::ExtraDataType::kCellWaterType:
            return "ExtraCellWaterType";
        case RE::ExtraDataType::kRegionList:
            return "ExtraRegionList";
        case RE::ExtraDataType::kSeenData:
            return "ExtraSeenData";
        case RE::ExtraDataType::kEditorID:
            return "ExtraEditorID";
        case RE::ExtraDataType::kCellMusicType:
            return "ExtraCellMusicType";
        case RE::ExtraDataType::kCellSkyRegion:
            return "ExtraCellSkyRegion";
        case RE::ExtraDataType::kProcessMiddleLow:
            return "ExtraProcessMiddleLow";
        case RE::ExtraDataType::kDetachTime:
            return "ExtraDetachTime";
        case RE::ExtraDataType::kPersistentCell:
            return "ExtraPersistentCell";
        case RE::ExtraDataType::kUnk0C:
            return "Unk0C";
        case RE::ExtraDataType::kAction:
            return "ExtraAction";
        case RE::ExtraDataType::kStartingPosition:
            return "ExtraStartingPosition";
        case RE::ExtraDataType::kUnk0F:
            return "Unk0F";
        case RE::ExtraDataType::kAnimGraphManager:
            return "ExtraAnimGraphManager";
        case RE::ExtraDataType::kBiped:
            return "ExtraBiped";
        case RE::ExtraDataType::kUsedMarkers:
            return "ExtraUsedMarkers";
        case RE::ExtraDataType::kDistantData:
            return "ExtraDistantData";
        case RE::ExtraDataType::kRagDollData:
            return "ExtraRagDollData";
        case RE::ExtraDataType::kContainerChanges:
            return "ExtraContainerChanges";
        case RE::ExtraDataType::kWorn:
            return "ExtraWorn";
        case RE::ExtraDataType::kWornLeft:
            return "ExtraWornLeft";
        case RE::ExtraDataType::kPackageStartLocation:
            return "ExtraPackageStartLocation";
        case RE::ExtraDataType::kPackage:
            return "ExtraPackage";
        case RE::ExtraDataType::kTresPassPackage:
            return "ExtraTresPassPackage";
        case RE::ExtraDataType::kRunOncePacks:
            return "ExtraRunOncePacks";
        case RE::ExtraDataType::kReferenceHandle:
            return "ExtraReferenceHandle";
        case RE::ExtraDataType::kFollower:
            return "ExtraFollower";
        case RE::ExtraDataType::kLevCreaModifier:
            return "ExtraLevCreaModifier";
        case RE::ExtraDataType::kGhost:
            return "ExtraGhost";
        case RE::ExtraDataType::kOriginalReference:
            return "ExtraOriginalReference";
        case RE::ExtraDataType::kOwnership:
            return "ExtraOwnership";
        case RE::ExtraDataType::kGlobal:
            return "ExtraGlobal";
        case RE::ExtraDataType::kRank:
            return "ExtraRank";
        case RE::ExtraDataType::kCount:
            return "ExtraCount";
        case RE::ExtraDataType::kHealth:
            return "ExtraHealth";
        case RE::ExtraDataType::kUnk26:
            return "Unk26";
        case RE::ExtraDataType::kTimeLeft:
            return "ExtraTimeLeft";
        case RE::ExtraDataType::kCharge:
            return "ExtraCharge";
        case RE::ExtraDataType::kLight:
            return "ExtraLight";
        case RE::ExtraDataType::kLock:
            return "ExtraLock";
        case RE::ExtraDataType::kTeleport:
            return "ExtraTeleport";
        case RE::ExtraDataType::kMapMarker:
            return "ExtraMapMarker";
        case RE::ExtraDataType::kLeveledCreature:
            return "ExtraLeveledCreature";
        case RE::ExtraDataType::kLeveledItem:
            return "ExtraLeveledItem";
        case RE::ExtraDataType::kScale:
            return "ExtraScale";
        case RE::ExtraDataType::kMissingLinkedRefIDs:
            return "ExtraMissingLinkedRefIDs";
        case RE::ExtraDataType::kMagicCaster:
            return "ExtraMagicCaster";
        case RE::ExtraDataType::kNonActorMagicTarget:
            return "NonActorMagicTarget";
        case RE::ExtraDataType::kUnk33:
            return "Unk33";
        case RE::ExtraDataType::kPlayerCrimeList:
            return "ExtraPlayerCrimeList";
        case RE::ExtraDataType::kUnk35:
            return "Unk35";
        case RE::ExtraDataType::kEnableStateParent:
            return "ExtraEnableStateParent";
        case RE::ExtraDataType::kEnableStateChildren:
            return "ExtraEnableStateChildren";
        case RE::ExtraDataType::kItemDropper:
            return "ExtraItemDropper";
        case RE::ExtraDataType::kDroppedItemList:
            return "ExtraDroppedItemList";
        case RE::ExtraDataType::kRandomTeleportMarker:
            return "ExtraRandomTeleportMarker";
        case RE::ExtraDataType::kUnk3B:
            return "Unk3B";
        case RE::ExtraDataType::kSavedHavokData:
            return "ExtraSavedHavokData";
        case RE::ExtraDataType::kCannotWear:
            return "ExtraCannotWear";
        case RE::ExtraDataType::kPoison:
            return "ExtraPoison";
        case RE::ExtraDataType::kMagicLight:
            return "ExtraMagicLight";
        case RE::ExtraDataType::kLastFinishedSequence:
            return "ExtraLastFinishedSequence";
        case RE::ExtraDataType::kSavedAnimation:
            return "ExtraSavedAnimation";
        case RE::ExtraDataType::kNorthRotation:
            return "ExtraNorthRotation";
        case RE::ExtraDataType::kSpawnContainer:
            return "ExtraSpawnContainer";
        case RE::ExtraDataType::kFriendHits:
            return "ExtraFriendHits";
        case RE::ExtraDataType::kHeadingTarget:
            return "ExtraHeadingTarget";
        case RE::ExtraDataType::kUnk46:
            return "Unk46";
        case RE::ExtraDataType::kRefractionProperty:
            return "ExtraRefractionProperty";
        case RE::ExtraDataType::kStartingWorldOrCell:
            return "ExtraStartingWorldOrCell";
        case RE::ExtraDataType::kHotkey:
            return "ExtraHotkey";
        case RE::ExtraDataType::kEditorRef3DData:
            return "ExtraEditorRef3DData";
        case RE::ExtraDataType::kEditorRefMoveData:
            return "ExtraEditorRefMoveData";
        case RE::ExtraDataType::kInfoGeneralTopic:
            return "ExtraInfoGeneralTopic";
        case RE::ExtraDataType::kHasNoRumors:
            return "ExtraHasNoRumors";
        case RE::ExtraDataType::kSound:
            return "ExtraSound";
        case RE::ExtraDataType::kTerminalState:
            return "ExtraTerminalState";
        case RE::ExtraDataType::kLinkedRef:
            return "ExtraLinkedRef";
        case RE::ExtraDataType::kLinkedRefChildren:
            return "ExtraLinkedRefChildren";
        case RE::ExtraDataType::kActivateRef:
            return "ExtraActivateRef";
        case RE::ExtraDataType::kActivateRefChildren:
            return "ExtraActivateRefChildren";
        case RE::ExtraDataType::kCanTalkToPlayer:
            return "ExtraCanTalkToPlayer";
        case RE::ExtraDataType::kObjectHealth:
            return "ExtraObjectHealth";
        case RE::ExtraDataType::kCellImageSpace:
            return "ExtraCellImageSpace";
        case RE::ExtraDataType::kNavMeshPortal:
            return "ExtraNavMeshPortal";
        case RE::ExtraDataType::kModelSwap:
            return "ExtraModelSwap";
        case RE::ExtraDataType::kRadius:
            return "ExtraRadius";
        case RE::ExtraDataType::kUnk5A:
            return "Unk5A";
        case RE::ExtraDataType::kFactionChanges:
            return "ExtraFactionChanges";
        case RE::ExtraDataType::kDismemberedLimbs:
            return "ExtraDismemberedLimbs";
        case RE::ExtraDataType::kActorCause:
            return "ExtraActorCause";
        case RE::ExtraDataType::kMultiBound:
            return "ExtraMultiBound";
        case RE::ExtraDataType::kMultiBoundMarkerData:
            return "MultiBoundMarkerData";
        case RE::ExtraDataType::kMultiBoundRef:
            return "ExtraMultiBoundRef";
        case RE::ExtraDataType::kReflectedRefs:
            return "ExtraReflectedRefs";
        case RE::ExtraDataType::kReflectorRefs:
            return "ExtraReflectorRefs";
        case RE::ExtraDataType::kEmittanceSource:
            return "ExtraEmittanceSource";
        case RE::ExtraDataType::kUnk64:
            return "Unk64";
        case RE::ExtraDataType::kCombatStyle:
            return "ExtraCombatStyle";
        case RE::ExtraDataType::kUnk66:
            return "Unk66";
        case RE::ExtraDataType::kPrimitive:
            return "ExtraPrimitive";
        case RE::ExtraDataType::kOpenCloseActivateRef:
            return "ExtraOpenCloseActivateRef";
        case RE::ExtraDataType::kAnimNoteReceiver:
            return "ExtraAnimNoteReceiver";
        case RE::ExtraDataType::kAmmo:
            return "ExtraAmmo";
        case RE::ExtraDataType::kPatrolRefData:
            return "ExtraPatrolRefData";
        case RE::ExtraDataType::kPackageData:
            return "ExtraPackageData";
        case RE::ExtraDataType::kOcclusionShape:
            return "ExtraOcclusionShape";
        case RE::ExtraDataType::kSayTopicInfoOnceADay:
            return "ExtraSayTopicInfoOnceADay";
        case RE::ExtraDataType::kEncounterZone:
            return "ExtraEncounterZone";
        case RE::ExtraDataType::kSayTopicInfo:
            return "ExtraSayToTopicInfo";
        case RE::ExtraDataType::kOcclusionPlaneRefData:
            return "ExtraOcclusionPlaneRefData";
        case RE::ExtraDataType::kPortalRefData:
            return "ExtraPortalRefData";
        case RE::ExtraDataType::kPortal:
            return "ExtraPortal";
        case RE::ExtraDataType::kRoom:
            return "ExtraRoom";
        case RE::ExtraDataType::kHealthPerc:
            return "ExtraHealthPerc";
        case RE::ExtraDataType::kRoomRefData:
            return "ExtraRoomRefData";
        case RE::ExtraDataType::kGuardedRefData:
            return "ExtraGuardedRefData";
        case RE::ExtraDataType::kCreatureAwakeSound:
            return "ExtraCreatureAwakeSound";
        case RE::ExtraDataType::kUnk7A:
            return "Unk7A";
        case RE::ExtraDataType::kHorse:
            return "ExtraHorse";
        case RE::ExtraDataType::kIgnoredBySandbox:
            return "ExtraIgnoredBySandbox";
        case RE::ExtraDataType::kCellAcousticSpace:
            return "ExtraCellAcousticSpace";
        case RE::ExtraDataType::kReservedMarkers:
            return "ExtraReservedMarkers";
        case RE::ExtraDataType::kWeaponIdleSound:
            return "ExtraWeaponIdleSound";
        case RE::ExtraDataType::kWaterLightRefs:
            return "ExtraWaterLightRefs";
        case RE::ExtraDataType::kLitWaterRefs:
            return "ExtraLitWaterRefs";
        case RE::ExtraDataType::kWeaponAttackSound:
            return "ExtraWeaponAttackSound";
        case RE::ExtraDataType::kActivateLoopSound:
            return "ExtraActivateLoopSound";
        case RE::ExtraDataType::kPatrolRefInUseData:
            return "ExtraPatrolRefInUseData";
        case RE::ExtraDataType::kAshPileRef:
            return "ExtraAshPileRef";
        case RE::ExtraDataType::kCreatureMovementSound:
            return "ExtraCreatureMovementSound";
        case RE::ExtraDataType::kFollowerSwimBreadcrumbs:
            return "ExtraFollowerSwimBreadcrumbs";
        case RE::ExtraDataType::kAliasInstanceArray:
            return "ExtraAliasInstanceArray";
        case RE::ExtraDataType::kLocation:
            return "ExtraLocation";
        case RE::ExtraDataType::kUnk8A:
            return "Unk8A";
        case RE::ExtraDataType::kLocationRefType:
            return "ExtraLocationRefType";
        case RE::ExtraDataType::kPromotedRef:
            return "ExtraPromotedRef";
        case RE::ExtraDataType::kAnimationSequencer:
            return "ExtraAnimationSequencer";
        case RE::ExtraDataType::kOutfitItem:
            return "ExtraOutfitItem";
        case RE::ExtraDataType::kUnk8F:
            return "Unk8F";
        case RE::ExtraDataType::kLeveledItemBase:
            return "ExtraLeveledItemBase";
        case RE::ExtraDataType::kLightData:
            return "ExtraLightData";
        case RE::ExtraDataType::kSceneData:
            return "ExtraSceneData";
        case RE::ExtraDataType::kBadPosition:
            return "ExtraBadPosition";
        case RE::ExtraDataType::kHeadTrackingWeight:
            return "ExtraHeadTrackingWeight";
        case RE::ExtraDataType::kFromAlias:
            return "ExtraFromAlias";
        case RE::ExtraDataType::kShouldWear:
            return "ExtraShouldWear";
        case RE::ExtraDataType::kFavorCost:
            return "ExtraFavorCost";
        case RE::ExtraDataType::kAttachedArrows3D:
            return "ExtraAttachedArrows3D";
        case RE::ExtraDataType::kTextDisplayData:
            return "ExtraTextDisplayData";
        case RE::ExtraDataType::kAlphaCutoff:
            return "ExtraAlphaCutoff";
        case RE::ExtraDataType::kEnchantment:
            return "ExtraEnchantment";
        case RE::ExtraDataType::kSoul:
            return "ExtraSoul";
        case RE::ExtraDataType::kForcedTarget:
            return "ExtraForcedTarget";
        case RE::ExtraDataType::kUnk9E:
            return "Unk9E";
        case RE::ExtraDataType::kUniqueID:
            return "ExtraUniqueID";
        case RE::ExtraDataType::kFlags:
            return "ExtraFlags";
        case RE::ExtraDataType::kRefrPath:
            return "ExtraRefrPath";
        case RE::ExtraDataType::kDecalGroup:
            return "ExtraDecalGroup";
        case RE::ExtraDataType::kLockList:
            return "ExtraLockList";
        case RE::ExtraDataType::kForcedLandingMarker:
            return "ExtraForcedLandingMarker";
        case RE::ExtraDataType::kLargeRefOwnerCells:
            return "ExtraLargeRefOwnerCells";
        case RE::ExtraDataType::kCellWaterEnvMap:
            return "ExtraCellWaterEnvMap";
        case RE::ExtraDataType::kCellGrassData:
            return "ExtraCellGrassData";
        case RE::ExtraDataType::kTeleportName:
            return "ExtraTeleportName";
        case RE::ExtraDataType::kInteraction:
            return "ExtraInteraction";
        case RE::ExtraDataType::kWaterData:
            return "ExtraWaterData";
        case RE::ExtraDataType::kWaterCurrentZoneData:
            return "ExtraWaterCurrentZoneData";
        case RE::ExtraDataType::kAttachRef:
            return "ExtraAttachRef";
        case RE::ExtraDataType::kAttachRefChildren:
            return "ExtraAttachRefChildren";
        case RE::ExtraDataType::kGroupConstraint:
            return "ExtraGroupConstraint";
        case RE::ExtraDataType::kScriptedAnimDependence:
            return "ExtraScriptedAnimDependence";
        case RE::ExtraDataType::kCachedScale:
            return "ExtraCachedScale";
        case RE::ExtraDataType::kRaceData:
            return "ExtraRaceData";
        case RE::ExtraDataType::kGIDBuffer:
            return "ExtraGIDBuffer";
        case RE::ExtraDataType::kMissingRefIDs:
            return "ExtraMissingRefIDs";
        case RE::ExtraDataType::kUnkB4:
            return "UnkB4";
        case RE::ExtraDataType::kResourcesPreload:
            return "ExtraResourcesPreload";
        case RE::ExtraDataType::kUnkB6:
            return "UnkB6";
        case RE::ExtraDataType::kUnkB7:
            return "UnkB7";
        case RE::ExtraDataType::kUnkB8:
            return "UnkB8";
        case RE::ExtraDataType::kUnkB9:
            return "UnkB9";
        case RE::ExtraDataType::kUnkBA:
            return "UnkBA";
        case RE::ExtraDataType::kUnkBB:
            return "UnkBB";
        case RE::ExtraDataType::kUnkBC:
            return "UnkBC";
        case RE::ExtraDataType::kUnkBD:
            return "UnkBD";
        case RE::ExtraDataType::kUnkBE:
            return "UnkBE";
        case RE::ExtraDataType::kUnkBF:
            return "UnkBF";
        default:
            return "Unknown";
    }
}